server:
  port: 8848

spring :
  application:
    name: provider
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 5

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml